export type { RawEditorEvent, RawCodingEvent, RawClipboardMarker, RawSnapshot } from './types/raw-events'
export type { DetectorResult, DetectorFunction, DetectorRegistry, DetectorInput } from './types/detector'
export type { RuleConfig } from './types/rules'
export type { EngineInput, EngineOutput, BehaviorState } from './types/engine'
export type { BehaviorIntelligenceAdapter } from './types/adapter'
export { BrainEngine, createBrain, createBrainWithPreset, InputLayer, ProcessingLayer, DecisionLayer, OutputLayer } from './brain'
export type { BrainInput, NormalizedInput, NormalizedEvent, NormalizedSnapshot, SessionMetadata, ProcessingOutput, DecisionOutput, BrainOutput, BrainConfig } from './brain/types'
export { DEFAULT_BRAIN_CONFIG, STRICT_BRAIN_CONFIG, LENIENT_BRAIN_CONFIG, TEST_BRAIN_CONFIG, getBrainConfig } from './brain/config'
export { runEngine } from './engine/run-engine'
export { aggregateDetectorResults, simpleAggregate } from './engine/aggregate'
export { runBehaviorAnalysis, runBehaviorAnalysisWithInput } from './engine/run-behavior-analysis'
export { default as detectorRegistry } from './detectors'
export { getDetector, getDetectorNames, runDetector, runAllDetectors } from './detectors'
export { default as pasteRatioDetector } from './detectors/paste-ratio.detector'
export { default as burstInsertionDetector } from './detectors/burst-insertion.detector'
export { default as typingRhythmDetector } from './detectors/typing-rhythm.detector'
export { default as editLocalityDetector } from './detectors/edit-locality.detector'
export * as stats from './utils/stats'
export * as time from './utils/time'
export * as diff from './utils/diff'
export const VERSION = '1.0.0'
export const PACKAGE_NAME = 'behavior-intelligence'